name: main

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Angular - npm install
      run: |
        cd src/angular-app
        npm install
    - name: Angular - npm run build
      run: |
        cd src/angular-app
        npm run build
